spring:
  datasource:
    url: jdbc:mysql://localhost:3306/revworkforcep2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: RevWorkForceSecretKeyForJwtTokenGeneration12345
    expiration-ms: 86400000

logging:
  level:
    root: INFO
    com.revworkforce: DEBUG
