server:
  port: 8083

spring:
  application:
    name: leave-service
  datasource:
    url: jdbc:h2:mem:leavedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

leave:
  total-allocated: 24

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j:
  circuitbreaker:
    instances:
      employee-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
