# ===============================
# SERVER
# ===============================
server.port=8084

# ===============================
# MYSQL DATABASE CONFIG
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/vault_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Akhila@28

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always

# ===============================
# FILE UPLOAD CONFIG
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# BACKUP STORAGE LOCATION
# ===============================
backup.storage.path=backup/

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.com.passwordmanager=DEBUG

# ===============================
# JWT
# ===============================
jwt.secret=replace-with-a-long-random-secret-key-1234567890
jwt.expiration=86400000

# ===============================
# VAULT ENCRYPTION
# ===============================
vault.encryption.key=MySuperSecretKey123
